### list tasks
GET http://localhost:3000/tasks

### list task
GET http://localhost:3000/tasks/1

### create task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "name": "teste 1", 
  "description": "descrição do teste1"
}

### patch task
PATCH http://localhost:3000/tasks/1

### delete task
DELETE http://localhost:3000/tasks/1